### ISSUE TITLE
Open for PR? Laravel 5.7 support (autodiscovery)

### ISSUE THREAD

**Issue by martijn94** [huddledigital/zendesk-laravel#11]
Hi,

Are you open for PR to add support up to Laravel 5.7? Mainly package autodiscovery.

Thanks

**Comment by harry-huddle** [comment]
More than happy, send a PR and we'll take a look.

Harry


   *Harry Potts*
Founder & Technical Director
<http://workwithhuddle.com>    *Huddle Digital*  <http://workwithhuddle.com>
workwithhuddle.com  <http://workwithhuddle.com>   0161 327 2827
<01613272827>   @huddledigital <http://twitter.com/huddledigital>
   [image: Big Chip Awards] <http://www.bigchipawards.com>      [image:
Greater Manchester Chamber of Commerce] <https://www.gmchamber.co.uk/>
     [image:
Manchester Digital] <https://www.manchesterdigital.com/>      [image:
Innovation 100] <http://www.bqlive.co.uk/section/218/innovation-100>
This email is commercial in confidence. *Terms
<http://workwithhuddle.com/terms-conditions>*

**Comment by martijn94** [comment]
hey Harry,

Thanks im on it, just wanted to make sure it will be merged.
