### ISSUE TITLE
Updated composer Laravel 5.3

### ISSUE THREAD

**Issue by tiagocardosos** [huddledigital/zendesk-laravel#5]

**Comment by ghermans** [comment]
is there any update regarding this?

**Comment by sebnyc** [comment]
Hi guys,
Any update on this ?
We really need a Laravel 5.3 update available in packagist, and it looks like you are the only ones who can do that.
Thank you so much.

**Comment by harry-huddle** [comment]
Anyone is welcome to submit a pull request with any amends they want to make and we'll look into it.
